/*
 --//am 20140815 find a way to NOT use so many scripts
 Script: testdb1.HABITATE.schema.3.sql
 Description: Creates Tables
 */
--DROP SCHEMA HABITATE CASCADE IF EXISTS;
CREATE SCHEMA HABITATE AUTHORIZATION DBA;
SET SCHEMA HABITATE;

DROP TABLE country IF EXISTS;
CREATE TABLE country (country_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY, country_name varchar(30) not null);
--CREATE TABLE country (country_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY, country_name varchar(30) not null UNIQUE);
--CREATE TABLE country (country_id INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1) PRIMARY KEY, country_name varchar(30) not null UNIQUE);
--CREATE TABLE country (country_id INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1) PRIMARY KEY, country_name varchar(30) not null CHECK (country_name <> '') UNIQUE);

DROP TABLE province IF EXISTS CASCADE;
CREATE TABLE province (province_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY, province_name varchar(30) not null);
--CREATE TABLE province (province_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1)PRIMARY KEY, province_name varchar(30) not null UNIQUE);

DROP TABLE town IF EXISTS CASCADE;
-- CREATE TABLE town (town_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1)PRIMARY KEY, town_name varchar(30) not null CHECK (town_name <> ''), population integer not null);
CREATE TABLE town (town_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY, town_name varchar(30) not null, population integer not null);

-- Country-Province link
DROP TABLE country_province IF EXISTS;
CREATE TABLE country_province (id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY, country_id INTEGER not null, province_id INTEGER not null, last_modify TIMESTAMP);
--CREATE TABLE country_province (id INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1) PRIMARY KEY, country_id INTEGER not null, province_id INTEGER not null, last_modify TIMESTAMP);
--ALTER TABLE country_province ADD CONSTRAINT fk1 FOREIGN KEY (country_id) REFERENCES country (country_id);
--ALTER TABLE country_province ADD CONSTRAINT fk2 FOREIGN KEY (province_id) REFERENCES province (province_id);

-- Province-Town link
--DROP SEQUENCE seq_1 IF EXISTS CASCADE;
--CREATE SEQUENCE seq_1 START with 1;

DROP TABLE IF EXISTS province_town CASCADE;
CREATE TABLE province_town (id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY, province_id INTEGER not null, town_id INTEGER not null, last_modify TIMESTAMP);
--CREATE TABLE province_town (id INTEGER GENERATED BY DEFAULT AS SEQUENCE seq_1 PRIMARY KEY, province_id INTEGER not null, town_id INTEGER not null, last_modify TIMESTAMP);
--ALTER TABLE province_town ADD CONSTRAINT fk3 FOREIGN KEY (province_id) REFERENCES province (province_id);
--ALTER TABLE province_town ADD CONSTRAINT fk4 FOREIGN KEY (town_id) REFERENCES town (town_id);




